mepa: lan8814: Stop using float numbers
When importing MESA in VelocitySP, it would start to fail to build with
the error:

/usr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../riscv64-unknown-elf/bin/ld: third-party/mesa/mepa/libmepa_velocitysp_lan969x.a(lan8814.obj): in function `lan8814_cab_diag_read_result':
lan8814.c:(.text.lan8814_cab_diag_read_result+0x5e): undefined reference to `__floatunsidf'
/usr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../riscv64-unknown-elf/bin/ld: lan8814.c:(.text.lan8814_cab_diag_read_result+0x78): undefined reference to `__fixunsdfsi'
collect2: error: ld returned 1 exit status

Therefore change the logic to stop using float numbers.